version: '3.7'
services:
  oracle:
    image: oracleinanutshell/oracle-xe-11g:latest
    hostname: oracle
    container_name: oracle
    ports:
      - "49161:1521"
      - "5500:5500"
    environment:
      ORACLE_ALLOW_REMOTE: "true"
      ORACLE_DISABLE_ASYNCH_IO: "true"
    volumes:
      - ./scripts/oracle:/docker-entrypoint-initdb.d
  jboss-fuse:
    image: jboss-fuse-eap-7.9.0:1.0-SNAPSHOT
    hostname: jboss-fuse
    container_name: jboss-fuse
    depends_on:
      - oracle
    ports:
      - "18080:8080"
      - "19990:9990"
      - "18443:8443"
    environment:
      JAVA_OPTS: "-Doracle.jdbc.timezoneAsRegion=false -Djboss.server.default.config=standalone.xml -Djboss.http.port=8080 -Djboss.management.http.port=9990 -Dapp.context.root=test -Djboss.bind.address=0.0.0.0 -Djboss.bind.address.management=0.0.0.0"
    healthcheck:
      test: ["CMD", "curl -f http://localhost:9990/health/ready || exit 1"]
      timeout: 60s
      interval: 5s
      retries: 10
  swagger-ui:
    image: swaggerapi/swagger-ui
    hostname: swagger-ui
    container_name: swagger-ui
    ports:
      - "80:8080"
    environment:
      BASE_URL: http://localhost:80/plan-journey-jax-rs/tfp/journeys
